### ISSUE TITLE
Compatibility with bundleless Symfony 4 structure

### ISSUE THREAD

**Issue by maxailloud** [atoum/AtoumBundle#111]
The bundle is not working with the new file structure for Symfony 4.
It's expecting a bundle but as for now it's possible to not have one, and so the message `Bundle "App" does not exists` appears, which makes sense as App is not a bundle. 

Maybe I missed something existing to make it work, and if it's the case pointing it to me would be nice, or we need to change the [BundleDirectoriesResolverPass](https://github.com/atoum/AtoumBundle/blob/master/DependencyInjection/Compiler/BundleDirectoriesResolverPass.php) to take into account this case.

**Comment by Grummfy** [comment]
thanks for the report, not sure when we we handle it

**Comment by maxailloud** [comment]
Sure no worries.
I will try to find a solution too in the meantime, maybe i can do something.

**Comment by Grummfy** [comment]
We accept PR. For now, our main dev that knows symfony is really busy so it's hard to dig in this bundle by ourself. Don't hesitate to make a PR with in the title work in progress ([WIP]).

thanks
