### ISSUE TITLE
No assert in WebTestCase

### ISSUE THREAD

**Issue by ekitakata** [atoum/AtoumBundle#86]
Hi,

I make a simple test class who extends WebTestCase

```php
namespace COmpany\TotoBundle\Tests\Units\Controller;

use atoum\AtoumBundle\Test\Units\WebTestCase;

class AuthenticationController extends WebTestCase
{

    public function testLogoutAction()
    {
        $this->request()
                ->GET('/logout')
                    ->hasStatus(302)
                    ->hasCharset('UTF-8')
                ->GET('/logout/')
                    ->hasStatus(404)
        ;
    }
}
```

When i play this test, test pass but the result is 

Success (1 test, 0/1 method, 1 void method, 0 skipped method, 0 assertion)!

0 assertion : it's normal or due to my environment ?

environment : PHP 5.6.11-1+deb.sury.org~trusty+1 (cli)
=> Copyright (c) 1997-2015 The PHP Group
=> Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
=>     with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
=>     with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans

Thanks in advance

**Comment by jubianchi** [comment]
> 0 assertion : it's normal or due to my environment ?

I think this is a bug :)

**Comment by ekitakata** [comment]
yes it run and fail with "success" 

i've test in other environment (php 5.5.9) and same results test fail good but pass with 0 assertions.

So it seem's little non blocking bug.

**Comment by Tom32i** [comment]
Same problem here.

**Comment by fabdsp** [comment]
:+1:

**Comment by ektarum** [comment]
bump @jubianchi

**Comment by jubianchi** [comment]
should we close this now that the #87 is merged ?

**Comment by FlorianLB** [comment]
Yep
