### ISSUE TITLE
[SF3] Symfony3 compatibility

### ISSUE THREAD

**Issue by aliel** [atoum/AtoumBundle#90]
AtoumBundle require the ''2.*'  version of Finder package and at the same time Symfony 3.0 require 'self.version' => '3.0'.

It's the same probleme with other dependencies (dom-crawler, ...)

thank's

**Comment by FlorianLB** [comment]
Indeed, it's a more global issue. We can't just change `composer.json` requirements, we must check if we use some deprecated features that are removed in 3.0.

**Comment by aliel** [comment]
Pull request => https://github.com/atoum/AtoumBundle/pull/91

**Comment by FlorianLB** [comment]
https://github.com/atoum/AtoumBundle/releases/tag/1.4.0

**Comment by aliel** [comment]
Thanks :)
