### ISSUE TITLE
CssSelector removed in symfony 3

### ISSUE THREAD

**Issue by bGaetan** [atoum/AtoumBundle#96]
Hi all,

Since symfony 3, the CssSelector class in Symfony\Component\CssSelector\ has been removed.

This class is used `atoum-bundle/atoum/AtoumBundle/Test/Units/WebTestCase.php`, when we set the handler on 'crawler'. 

So, it's not possible to use something like :

`->crawler
    ->hasElement('#contact_form')
        ->hasChild('input')->exactly(3)->end()
        ->hasChild('input')
`

**Comment by lolautruche** [comment]
I have the same issue 😢
