### ISSUE TITLE
Bad exit value for the command

### ISSUE THREAD

**Issue by maxailloud** [atoum/AtoumBundle#97]
The command always end with a 0 exit code, even if the tests failed.
Is it possible to have it return an error code if necessary, as using atoum directly I would guess?

**Comment by jubianchi** [comment]
@maxailloud https://github.com/atoum/AtoumBundle/releases/tag/1.4.1

**Comment by maxailloud** [comment]
I'll need packagist to get the new tag but thank for the quick respond.

**Comment by jubianchi** [comment]
Sorry @maxailloud, packagist did not auto-update. I triggered the update manually, the tag is no available there ;)
